### ISSUE TITLE
Отступы

### ISSUE THREAD

**Issue by A1daris** [Irinkes/todolist#2]
https://github.com/Irinkes/todolist/blob/a53e53800c8f7555996aed875a17a9cbcb82b069/src/components/list.js#L10
три пустых строки подряд не улучшают читаемость. старайся больше одной не ставить.
табуляцию хочется сделать поменьше, код очень быстро уезжает за правый край экрана.
название файла с большой буквы

**Comment by Irinkes** [comment]
убрала пустые строчки, и все файлы переименовала
